
[context.production]
  command = "yarn build-production"
  publish = ".next"
  [context.production.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='production'
    NEXT_PUBLIC_GOOGLE_CLOUD_PROJECT_ID = 'syndicate-382709'
    NEXT_PUBLIC_GOOGLE_CLOUD_BUCKET = 'syndicate_filestore_production'
    NEXT_PUBLIC_GOOGLE_CLIENT_ID = '691225200393-4m2a66oge9n5fp5hd43at845f1o9fn67.apps.googleusercontent.com'
    NEXT_PUBLIC_AUTH_HEADER = 'Db-Auth-Token'
    NEXT_PUBLIC_DGRAPH_ENDPOINT = 'https://blue-surf-1120002.us-east-1.aws.cloud.dgraph.io/graphql'
    NEXT_PUBLIC_SMTP_HOST= 'smtp.postmarkapp.com'
    NEXT_PUBLIC_SMTP_PORT= '25'
    NEXT_PUBLIC_SMTP_FROM= 'no-reply@cooperativ.io'
    NEXT_PUBLIC_NOTIFICATIONS_FROM = 'notifications@cooperativ.io'
    NEXT_PUBLIC_POSTMARK_HEADER= 'X-PM-Message-Stream: magic-link-stream'
    NEXTAUTH_URL = "https://syndicate.cooperativ.io"
    
[context.reizen]
  command = "yarn build-reizen"
  publish = ".next"
  [context.reizen.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='production'
    NEXT_PUBLIC_CLIENT = 'reizen'
    NEXT_PUBLIC_GOOGLE_CLOUD_PROJECT_ID = 'syndicate-382709'
    NEXT_PUBLIC_GOOGLE_CLOUD_BUCKET = 'syndicate_filestore_production'
    NEXT_PUBLIC_GOOGLE_CLIENT_ID = '691225200393-4m2a66oge9n5fp5hd43at845f1o9fn67.apps.googleusercontent.com'
    NEXT_PUBLIC_AUTH_HEADER = 'Db-Auth-Token'
    NEXT_PUBLIC_DGRAPH_ENDPOINT = 'https://blue-surf-1310073.us-east-1.aws.cloud.dgraph.io/graphql'
    NEXT_PUBLIC_SMTP_HOST= 'smtp.postmarkapp.com'
    NEXT_PUBLIC_SMTP_PORT= '25'
    NEXT_PUBLIC_SMTP_FROM= 'no-reply@reizen.xyz'
    NEXT_PUBLIC_NOTIFICATIONS_FROM = 'notifications@reizen.xyz'
    NEXT_PUBLIC_POSTMARK_HEADER= 'X-PM-Message-Stream: magic-link-stream'
    NEXTAUTH_URL = "https://syndicate.reizen.xyz"

[context.staging]
  command = "yarn build-staging"
  publish = ".next"
  [context.staging.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='staging'
    NEXT_PUBLIC_GOOGLE_CLOUD_PROJECT_ID = 'syndicate-382709'
    NEXT_PUBLIC_GOOGLE_CLOUD_BUCKET = 'cooperativ-filestore'
    NEXT_PUBLIC_GOOGLE_CLIENT_ID = '691225200393-ji1sriqa3lkr2lp373aphn74tfkf2j24.apps.googleusercontent.com'
    NEXT_PUBLIC_AUTH_HEADER = 'Db-Auth-Token'
    NEXT_PUBLIC_DGRAPH_ENDPOINT = 'https://blue-surf-960058.us-east-1.aws.cloud.dgraph.io/graphql'
    NEXT_PUBLIC_SMTP_HOST= 'smtp.postmarkapp.com'
    NEXT_PUBLIC_SMTP_PORT= '25'
    NEXT_PUBLIC_SMTP_FROM= 'no-reply@cooperativ.io'
    NEXT_PUBLIC_NOTIFICATIONS_FROM = 'notifications@cooperativ.io'
    NEXT_PUBLIC_POSTMARK_HEADER= 'X-PM-Message-Stream: magic-link-stream'
    NEXTAUTH_URL = "https://staging.syndicate.cooperativ.io"

