
[context.production]
  command = "yarn build-production"
  publish = ".next"
  [context.production.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='production'

[context.staging]
  command = "yarn build-staging"
  publish = ".next"
  [context.staging.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='staging'
    NEXT_PUBLIC_STAGING_FIREBASE_AUTH_DOMAIN = 'cooperativ-staging.firebaseapp.com'
    NEXT_PUBLIC_STAGING_FIREBASE_PROJECT_ID = 'cooperativ-staging'
    NEXT_PUBLIC_STAGING_FIREBASE_STORAGE_BUCKET = 'cooperativ-staging.appspot.com'
    NEXT_PUBLIC_STAGING_FIREBASE_MESSAGING_SENDER_ID = '33358597434'
    NEXT_PUBLIC_STAGING_FIREBASE_APP_ID = '1:33358597434:web:91ec13dacf84a3a232d403'
