
[context.production]
  command = "yarn build-production"
  publish = ".next"
  [context.production.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='production'
    NEXT_PUBLIC_GOOGLE_CLOUD_PROJECT_ID = 'syndicate-382709'
    NEXT_PUBLIC_GOOGLE_CLOUD_BUCKET = 'syndicate_filestore_production'
    NEXT_PUBLIC_AUTH_HEADER = 'X-Auth-Token'
    NEXT_PUBLIC_DGRAPH_ENDPOINT = ''

[context.staging]
  command = "yarn build-staging"
  publish = ".next"
  [context.staging.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='staging'
    NEXT_PUBLIC_GOOGLE_CLOUD_PROJECT_ID = 'syndicate-382709'
    NEXT_PUBLIC_GOOGLE_CLOUD_BUCKET = 'cooperativ-filestore'
    NEXT_PUBLIC_AUTH_HEADER = 'X-Auth-Token'
    NEXT_PUBLIC_DGRAPH_ENDPOINT = 'x
 

