
[context.production]
  command = "yarn build-production"
  publish = ".next"
  [context.production.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='production'
    NEXT_PUBLIC_GOOGLE_CLOUD_PROJECT_ID = 'syndicate-382709'
    NEXT_PUBLIC_GOOGLE_CLOUD_BUCKET = 'syndicate_filestore_production'
    NEXT_PUBLIC_AUTH_HEADER = 'X-Auth-Token'
       NEXT_PUBLIC_DGRAPH_ENDPOINT = 'https://blue-surf-1120002.us-east-1.aws.cloud.dgraph.io/graphql'
    NEXT_PUBLIC_EMAIL_SERVER= 'smtp://fb06b404-d3d7-494d-8a01-6fc6bfad2921:fb06b404-d3d7-494d-8a01-6fc6bfad2921@smtp.postmarkapp.com:587'
    NEXT_PUBLIC_SMTP_HOST= 'smtp.postmarkapp.com'
    NEXT_PUBLIC_SMTP_PORT= '25'
    NEXT_PUBLIC_SMTP_FROM= 'no-reply@cooperativ.io'
    NEXT_PUBLIC_POSTMARK_HEADER= 'X-PM-Message-Stream: magic-link-stream'


[context.staging]
  command = "yarn build-staging"
  publish = ".next"
  [context.staging.environment]
    NEXT_PUBLIC_DEPLOY_STAGE='staging'
    NEXT_PUBLIC_GOOGLE_CLOUD_PROJECT_ID = 'syndicate-382709'
    NEXT_PUBLIC_GOOGLE_CLOUD_BUCKET = 'cooperativ-filestore'
    NEXT_PUBLIC_AUTH_HEADER = 'X-Auth-Token'
    NEXT_PUBLIC_DGRAPH_ENDPOINT = 'https://blue-surf-960058.us-east-1.aws.cloud.dgraph.io/graphql'
    NEXT_PUBLIC_EMAIL_SERVER= 'smtp://fb06b404-d3d7-494d-8a01-6fc6bfad2921:fb06b404-d3d7-494d-8a01-6fc6bfad2921@smtp.postmarkapp.com:587'
    NEXT_PUBLIC_SMTP_HOST= 'smtp.postmarkapp.com'
    NEXT_PUBLIC_SMTP_PORT= '25'
    NEXT_PUBLIC_SMTP_FROM= 'no-reply@cooperativ.io'
    NEXT_PUBLIC_POSTMARK_HEADER= 'X-PM-Message-Stream: magic-link-stream'

